name: QA Bug Report
description: File a bug report during QA.
title: "[Bug]: "
labels: ["bug", "triage", "qa"]
projects: ["ABPIA-GRENOBLE/Dev"]
assignees:
  - taiamiti
body:
  - type: markdown
    attributes:
      value: |
        Guidelines for writing a ticket
        - **ticket title** : make sure to mention the problem encountered, summarized in the most understandable way possible
          Example : VAT and Total amounts are not calculated correctly
        - **ticket body** : complete each section of the below form precisely. Make sure to provide link to url and screenshots where the problem occurs.
  - type: input
    id: url
    attributes:
      label: URL where the bug happened
      description: Copy/paste the URL of the page from which the issue happened
      placeholder: ex. https://app.factoo.fr/workspace/8/group/9/folder
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What steps did I take and what was expected ?
      description: Describe the steps made and what did you expect to happen?
      placeholder: Enter your answer
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened ?
      description: Describe what bug happen?
      placeholder: Tell us what you see! Please copy and paste any relevant log output or screenshots to describe the issue.
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using ?
      options:
        - Google Chrome (default)
        - Firefox
        - Microsoft Edge
      default: 0
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low - Functionnality not working as expected. Simple and effective workaround available. Improvement desirable for user experience.
        - Major - Workaround available but not optimal. Requires immediate fix.
        - Critical - Significant impact on productivity or user experience. Requires urgent fix
    validations:
      required: true

