name: QA Bug Report
description: File a bug report during QA.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["ABPIA-GRENOBLE/Dev"]
assignees:
  - taiamiti
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What steps did I take and what was expected ?
      description: Describe the steps made and what did you expect to happen?
      placeholder: Enter your answer
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened ?
      description: Describe what bug happen?
      placeholder: Tell us what you see! Please copy and paste any relevant log output or screenshots to describe the issue.
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using ?
      options:
        - Google Chrome (default)
        - Firefox
        - Microsoft Edge
      default: 0
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low - Functionnality not working as expected. Simple and effective workaround available. Improvement desirable for user experience.
        - Major - Workaround available but not optimal. Requires immediate fix.
        - Critical - Significant impact on productivity or user experience. Requires urgent fix
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

